name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm run test
      - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: >-
          ${{
            github.event_name == 'push' &&
            !contains(join(github.event.commits.*.message, ' '), '#skip')
          }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  tag_release:
    if: >-
      ${{
        github.event_name == 'push' &&
        !contains(join(github.event.commits.*.message, ' '), '#skip')
      }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
  notify_discord:
    if: always()
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1.16.0
        if: >-
          ${{
            needs.simple_deployment_pipeline.result == 'success' &&
            github.event_name == 'push' &&
            !contains(join(github.event.commits.*.message, ' '), '#skip')
          }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: '**✅ Deployment successful!** A new version deployed to production'
          title: 'Deployment details'
          description: |
            **Commit:** `${{ github.sha }}`
            **Message:** `${{ github.event.head_commit.message || '<no message>' }}`
            **Author:** `${{ github.event.head_commit.author.name }}`
          color: 0x00ff00
          url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          username: GitHub Actions - LUKASZ-JK

      - uses: sarisia/actions-status-discord@v1.16.0
        if: >-
          ${{
            needs.simple_deployment_pipeline.result == 'failure'
          }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: '**❌ Build failed!** The pipeline encountered an error'
          title: 'Failure details'
          description: |
            **Repository:** `${{ github.repository }}`
            **Branch:** `${{ github.ref_name }}`
            **Commit:** `${{ github.sha }}`
            **Message:** `${{ github.event.head_commit.message || '<no message>' }}`
            **Author:** `${{ github.event.head_commit.author.name }}`
            **Workflow:** `${{ github.workflow }}`
            **Job:** `${{ github.job }}`
            **Release:** `${{ github.event.release.tag_name }}`

            [View Commit](${{ github.event.head_commit.url }})
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          color: 0xff0000
          username: GitHub Actions - LUKASZ-JK
